const express = require('express');
const bodyParser = require('body-parser');
const routes = require('./routes');
const ngrok = require('ngrok');
const {cache, cacheKeys} = require('./services/cache-service');
require('dotenv').config();

const {PORT: port} = process.env;
const app = express();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }))
app.use(routes);

app.listen(port, () => {
  ngrok.connect({
    addr: port,
    ...process.env.NGROK_SUBDOMAIN && { subdomain: process.env.NGROK_SUBDOMAIN }
  }).then(url => {
    // Store server base Url generated by NGROK (Used for the auth flow - `auth-controller.js`)
    cache.set(cacheKeys.SERVER_URL, url);
    console.log(`listening at localhost:${port} || tunnel: ${url}`);
  })
});

module.exports = app;
