const PORT = 'PORT';
const BASE_URL = 'BASE_URL';
const SERVICE_TAG_URL = 'SERVICE_TAG_URL';
const LOCAL_SERVER_URL = 'LOCAL_SERVER_URL';
const NODE_ENV = 'NODE_ENV';
const MONDAY_SIGNING_SECRET = 'MONDAY_SIGNING_SECRET';
const MONDAY_OAUTH_CLIENT_ID = 'MONDAY_OAUTH_CLIENT_ID';
const MONDAY_OAUTH_CLIENT_SECRET = 'MONDAY_OAUTH_CLIENT_SECRET';
const MONDAY_OAUTH_TOKEN_PATH = 'MONDAY_OAUTH_TOKEN_PATH';
const MONDAY_OAUTH_HOST = 'MONDAY_OAUTH_HOST';
const MONDAY_OAUTH_AUTHORIZE_PATH = 'MONDAY_OAUTH_AUTHORIZE_PATH';
const MONDAY_SCOPES = 'MONDAY_SCOPES'
const USERNAME = 'USERNAME'
const API_KEY = 'API_KEY'
const URL = 'URL'

module.exports = {
  PORT,
  BASE_URL,
  SERVICE_TAG_URL,
  LOCAL_SERVER_URL,
  NODE_ENV,
  MONDAY_SIGNING_SECRET,
  MONDAY_OAUTH_CLIENT_ID,
  MONDAY_OAUTH_CLIENT_SECRET,
  MONDAY_OAUTH_TOKEN_PATH,
  MONDAY_OAUTH_HOST,
  MONDAY_OAUTH_AUTHORIZE_PATH,
  MONDAY_SCOPES,
  USERNAME, 
  API_KEY,
  URL,
};
